### ISSUE TITLE
Endless loop on Ble-firmata request REPORT_VERSION

### ISSUE THREAD

**Issue by benoit-linard** [noopkat/blend-micro-io#3]
Hello,

I have a problem with the script, when I run nodejs I open the BLE, but after it endless loop on:

```
Ble-firmata request REPORT_VERSION +1s
```

The blendmicro is detected by debian with :

```
hcitool Lescan
```

and no problem to connect with :

```
gatttool -b xx: xx: xx: xx: xx: xx -I
```

Have you any idea?

Sorry for my english and thank you in advance.

**Comment by noopkat** [comment]
Hi, could you please paste what code you're running in NodeJS, even if it's just the sample script provided in the readme? Thanks!

**Comment by benoit-linard** [comment]
Hi,

Just readme script for nodejs and patched StandardFirmata v2.3 on the blendmicro.

Thanks

**Comment by noopkat** [comment]
thanks for the additional info. 

I suggest trying to connect with your BlendMicro by using just [node-ble-firmata](https://github.com/shokai/node-ble-firmata) without blend-micro-io first to see if you run into the same issue. Blend-micro-io is built on top of ble-firmata, so I'd like to isolate the issue to one of the libraries so we can progress further.

Thanks!

**Comment by benoit-linard** [comment]
Hi, 

Thank you for your answers, I tested node-ble-firmata, I have the same issue. I run my node js with:

```
DEBUG=ble-firmata node app.js
```

Thanks again.

**Comment by noopkat** [comment]
Thanks for testing this! I would recommend opening a ticket on
node-ble-firmata. I can watch the ticket, and pull in an update to
blend-micro-io once it's fixed.
If I figure out why it's broken, I'll pull request node-ble-firmata. I'll
see if I can get onto a linux machine with a BT4.0 dongle in the near
future to see if I can replicate.

**Comment by benoit-linard** [comment]
Thanks, I opened the same ticket on node-ble-firmata here : https://github.com/shokai/node-ble-firmata/issues/5
Thanks for your help.
